"""
Enterprise Report Package Model.

Represents the complete collection of report artifacts
generated by the InsightPilot AI reporting pipeline.

This model acts as the canonical output of the reporting layer
and provides a single object that can be consumed by storage,
API, export, and deployment services.
"""

from __future__ import annotations

from dataclasses import asdict
from dataclasses import dataclass
from dataclasses import field
from datetime import UTC
from datetime import datetime
from pathlib import Path
from typing import Any

from backend.models.html_report import HTMLReport
from backend.models.metadata import ReportMetadata
from backend.models.pdf_report import PDFReport


# ==========================================================
# Report Package
# ==========================================================


@dataclass(slots=True)
class ReportPackage:
    """
    Represents the complete package of generated reports.

    A ReportPackage may contain one or more report formats
    generated from the same ReportContext.

    Example
    -------
    HTML
    PDF
    JSON

    Future versions may also include:

    - Excel
    - Markdown
    - ZIP archive
    - API payload
    """

    metadata: ReportMetadata

    html_report: HTMLReport | None = None

    pdf_report: PDFReport | None = None

    json_report_path: str | None = None

    created_at: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )

    artifacts: dict[str, str] = field(
        default_factory=dict
    )

    metadata_extra: dict[str, Any] = field(
        default_factory=dict
    )

    # ======================================================
    # Convenience Helpers
    # ======================================================

    def has_html(self) -> bool:
        """
        Returns True if an HTML report exists.
        """

        return self.html_report is not None

    def has_pdf(self) -> bool:
        """
        Returns True if a PDF report exists.
        """

        return self.pdf_report is not None

    def has_json(self) -> bool:
        """
        Returns True if a JSON report exists.
        """

        return self.json_report_path is not None

    # ======================================================
    # Available Formats
    # ======================================================

    def available_formats(self) -> list[str]:
        """
        Returns all generated report formats.
        """

        formats: list[str] = []

        if self.has_html():
            formats.append("HTML")

        if self.has_pdf():
            formats.append("PDF")

        if self.has_json():
            formats.append("JSON")

        return formats

    # ======================================================
    # Artifact Management
    # ======================================================

    def add_artifact(
        self,
        name: str,
        path: str | Path,
    ) -> None:
        """
        Register an additional report artifact.
        """

        self.artifacts[name] = str(path)

    def get_artifact(
        self,
        name: str,
    ) -> str | None:
        """
        Retrieve an artifact path.
        """

        return self.artifacts.get(name)

    # ======================================================
    # Serialization
    # ======================================================

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the report package into a serializable dictionary.
        """

        data = asdict(self)

        data["created_at"] = self.created_at.isoformat()

        data["available_formats"] = self.available_formats()

        return data