"""
Domain model representing the complete Rule Engine report.
"""

from dataclasses import dataclass, field
from typing import List

from backend.models.rule_result import RuleResult


@dataclass(slots=True)
class RuleReport:
    """
    Aggregated report generated by the Rule Engine.
    """

    total_rules: int
    passed_rules: int
    failed_rules: int
    warning_rules: int

    overall_status: str

    results: List[RuleResult] = field(default_factory=list)